version: "3.8"

name: gridcoin
services:
  boinc:
    container_name: gridcoin_boinc
    build: ./boinc
    volumes:
      - boinc:/var/lib/boinc:z
    restart: always

  gridcoin:
    container_name: gridcoin_gridcoin
    build:
      context: ./gridcoin

      # Uncomment the needed architecture
      args:
        # amd64
        #DEB_FILE: https://github.com/gridcoin-community/Gridcoin-Research/releases/download/5.5.0.0/gridcoinresearchd_5.5.0.0.trixie-2_amd64.deb
        #DEB_FILE_SHA256: ef9bd110998cf2641d08f60a2b41f059e79a50ebb84844199979c832e4432d83

        # arm64
        #DEB_FILE: https://github.com/gridcoin-community/Gridcoin-Research/releases/download/5.5.0.0/gridcoinresearchd_5.5.0.0.trixie-2_arm64.deb
        #DEB_FILE_SHA256: 30f51471c70fd11f2a6cdc0389cca351e826ea655cf902faa4e41140593c0a0e

    # Uncomment the ports, when inbound connections should be allowed. Also make sure to allow the port in the firewall, for firewalld
    # e.g. with `firewall-cmd --permanent --add-port 32749/tcp` followed by `systemctl reload firewalld`.
    #ports:
    #  - "32749:32749"

    volumes:
      - ./bind-mount/gridcoin:/root/.GridcoinResearch:Z
      - boinc:/var/lib/boinc-client:z,ro
    restart: always

  fah:
    container_name: gridcoin_fah
    build:
      context: ./fah

      # Uncomment the needed architecture
      args:
        # amd64
        #DEB_FILE: https://download.foldingathome.org/releases/public/fah-client/debian-10-64bit/release/fah-client_8.3.18_amd64.deb

        # arm64
        #DEB_FILE: https://download.foldingathome.org/releases/public/fah-client/debian-stable-arm64/release/fah-client_8.3.18_arm64.deb

    volumes:
      - ./bind-mount/fah/fah.xml:/var/lib/fah-client/config.xml:Z
      - fah:/var/lib/fah-client:Z
    restart: always

volumes:
  boinc:
    driver: local
  fah:
    driver: local
